name: Pull requst context
on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited,reopened,synchronize]
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # checkout full tree
          fetch-depth: 0
      - name: Echo github
        run: |
          for commit in $(git rev-list origin/${{ github.base_ref }}..origin/${{ github.head_ref }}); do
              git checkout $commit
              npm run lint
          done
      - name: Echo event
        run: cat $GITHUB_EVENT_PATH