name: Pull requst context
on:
  workflow_dispatch:
  pull_request:
    branches: master
    types: [opened, edited,reopened,synchronize]
    paths-ignore:
      - '.github/workflows/*'
jobs:
  matrix_maker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # checkout full tree
          fetch-depth: 0
      - id: set-matrix
        run: |
          for commit in $(git rev-list origin/${{ github.base_ref }}..origin/${{ github.head_ref }}); do
            echo $cpmmit >> $GITHUB_OUTPUT
          done
          # echo $(git rev-list origin/${{ github.base_ref }}..origin/${{ github.head_ref }}) >> $GITHUB_OUTPUT
    outputs:
      matrix: ${{ toJSON(steps.set-matrix.outputs) }}
  tests:
    needs: matrix_maker
    strategy:
      matrix:
        sha: ${{fromJson(needs.matrix_maker.outputs.matrix)}}
    runs-on: ubuntu-latest
    steps:
      - name: Testing commit ${{matrix.sha}}
        run: echo here testing ${{matrix.sha}} commit
      # - uses: actions/checkout@v2
      #   with:
      #     # checkout full tree
      #     fetch-depth: 0
      # - name: Echo github
      #   run: |
      #     for commit in $(git rev-list origin/${{ github.base_ref }}..origin/${{ github.head_ref }}); do
      #         git checkout $commit
      #         npm ci
      #         npm run lint
      #     done
      # - name: Echo event
      #   run: cat $GITHUB_EVENT_PATH