name: Pull requst context
on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited,reopened,synchronize]
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Echo github
        run: echo "${{ toJSON(github.base_ref) }}"
      - name: Echo event
        run: cat $GITHUB_EVENT_PATH