name: Tests on PR
on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited,reopened,synchronize]
    paths-ignore:
      - '.github/workflows/*'
jobs:
  commis_testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Test each commit
        run: |
            npm ci # знаю что надо в каждом коммите качать зависимости но не успел с ошибкой разобраться
            for commit in $(git rev-list origin/${{ github.base_ref }}..origin/${{ github.head_ref }}); do
              git checkout $commit
              npm run test-ci
              npx playwright install --with-deps
              npm run e2e-ci
            done