name: Pull requst context
on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited,reopened,synchronize]
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Echo github
        run: echo git rev-list ${{ github.base_ref }}..${{ github.head_ref }}
      - name: Echo event
        run: cat $GITHUB_EVENT_PATH