name: Pull requst context
on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited,reopened,synchronize]
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # checkout full tree
          fetch-depth: 0
      - name: Echo github
        run: |
          echo $(git rev-list 'origin/'${{ github.base_ref }}..'origin/'${{ github.head_ref }})
          # for commit in $(); do
          #     git checkout $commit
          #     echo "run test"
          # done
      - name: Echo event
        run: cat $GITHUB_EVENT_PATH