name: Pull requst context
on:
  workflow_dispatch:
  pull_request:
    branches: master
    types: [opened, edited,reopened,synchronize]
    paths-ignore:
      - '.github/workflows/*'
jobs:
  matrix_maker:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set_matrix.outputs.matrix}}
    steps:
      - name: Set Dynamic Matrix
        id: set_matrix
        run: |
            matrixStringifiedObject="{\"include\":[{\"run\":\"run1\"},{\"run\":\"run2\"}]}"
            echo "::set-output name=matrix::$matrixStringifiedObject"
            # echo "{matrix}={$matrixStringifiedObject}" >> $GITHUB_OUTPUT
      - name: Check output
        run: echo $GITHUB_OUTPUT
  tests:
    needs: matrix_maker
    strategy:
      matrix: ${{fromJson(needs.matrix_maker.outputs.matrix)}}
    runs-on: ubuntu-latest
    steps:
      - name: Testing commit ${{matrix.run}}
        run: echo here testing ${{matrix.run}} commit
      # - uses: actions/checkout@v2
      #   with:
      #     # checkout full tree
      #     fetch-depth: 0
      # - name: Echo github
      #   run: |
      #     for commit in $(git rev-list origin/${{ github.base_ref }}..origin/${{ github.head_ref }}); do
      #         git checkout $commit
      #         npm ci
      #         npm run lint
      #     done
      # - name: Echo event
      #   run: cat $GITHUB_EVENT_PATH