name: Tests on PR
on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited,reopened,synchronize]
    paths-ignore:
      - '.github/workflows/*'
jobs:
  matrix_maker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # checkout full tree
          fetch-depth: 0
      - name: Test each commit
        run: |
            for commit in $(git rev-list ${{ github.base_ref }}..${{ github.head_ref }}); do
              git checkout $commit
              npm ci
              npm run test-ci
              npm run e2e-ci
            done