name: Tests on PR
on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited,reopened,synchronize]
    paths-ignore:
      - '.github/workflows/*'
jobs:
  commis_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Test commit
        uses: ./.github/workflows/linting.yml