name: On release tag
on:
  workflow_dispatch:
  push:
    branches:
    - master
    tags:
    - 'v[0-9]+'
    paths-ignore:
    - '.github/workflows/*'
jobs:
  Create_release_branch:
    runs-on: ubuntu-latest
    steps:
      - name: echo tag
        run: echo create release branch